version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:  
    commands:
      # run 'npm install' using versions 
      - npm i -g npm@latest
      - npm ci
  build:
    commands:
      - npm run build
    
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'
