version: 0.2

phases:
  install:
     runtime-versions:
      nodejs: 10
  pre_build:
    installCommands: 
      - npm i -g npm@latest
    commands:
      # run 'npm install' using versions 
      - npm ci
  build:
    commands:
      - npm run build
    
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'
